/* The catalogue. One table, many kinds — a Kubernetes migration and a black
   metal record are the same kind of object here, distinguished only by band.

   `band` maps to the IEC 60062 resistor colour code (see DESIGN.md). It is the
   only thing colour encodes in this system. Every band is paired with its kind
   name in the markup so colour is never the sole signal. */

type kind = {
  band: int,
  name: string,
  note: string,
}

type entry = {
  cat: string,
  band: int,
  name: string,
  description: string,
  spec: string,
  year: string,
  status: string,
  href: string,
  repo: string,
  image: string,
  featured: bool,
  containImage: bool,
  invertOnLight: bool,
}

let catalogueNo = "No.1"
let revision = "2026.07"

let kinds: array<kind> = [
  {band: 1, name: "Systems", note: "infrastructure & architecture"},
  {band: 2, name: "Products", note: "shipped applications"},
  {band: 3, name: "Games", note: "originals & ports"},
  {band: 4, name: "Writing", note: "essays & notes"},
  {band: 5, name: "Tools", note: "open source utilities"},
  {band: 6, name: "Recorded", note: "released music"},
  {band: 7, name: "Composed", note: "generated & written music"},
]

let blank = {
  cat: "",
  band: 8,
  name: "",
  description: "",
  spec: "",
  year: "",
  status: "",
  href: "",
  repo: "",
  image: "",
  featured: false,
  containImage: false,
  invertOnLight: false,
}

let entries: array<entry> = [
  /* 1 — Systems */
  {
    ...blank,
    cat: "AK 1-0011",
    band: 1,
    name: "Legacy ↔ AI Integration",
    description: "Integrating legacy applications with AI over MCP, and building scalable infrastructure, as Systems Architect at Veltra.",
    spec: "MCP · AWS · K8s",
    year: "2024→",
    status: "ACTIVE",
  },
  {
    ...blank,
    cat: "AK 1-0004",
    band: 1,
    name: "Embedded Processor Design",
    description: "PhD studies in embedded processor design and optimization, following an M.Sc. in Computer Science at Keio University.",
    spec: "Keio · Research",
    year: "2008",
    status: "ARCHIVED",
  },
  /* 2 — Products */
  {
    ...blank,
    cat: "AK 2-0142",
    band: 2,
    name: "SUDONE",
    description: "Scan a shelf barcode in-store and know in seconds if it really beats online prices — your own private price notebook.",
    spec: "Flutter · Barcode",
    year: "2026",
    status: "LIVE",
    href: "https://sudone.jp",
    image: "/sudone.webp",
    featured: true,
  },
  {
    ...blank,
    cat: "AK 2-0131",
    band: 2,
    name: "Vigil.today",
    description: "Smart reminder widget PWA that keeps you on track with recurring tasks.",
    spec: "SvelteKit · Firebase",
    year: "2025",
    status: "LIVE",
    href: "https://vigil.today",
    image: "/vigil-today.webp",
  },
  {
    ...blank,
    cat: "AK 2-0128",
    band: 2,
    name: "Skriv.ist",
    description: "Multiplatform ebook reader.",
    spec: "Multiplatform",
    year: "2025",
    status: "LIVE",
    href: "https://skriv.ist",
    image: "/skrivist_logo_3.webp",
    containImage: true,
  },
  {
    ...blank,
    cat: "AK 2-0119",
    band: 2,
    name: "Fablespun",
    description: "AI-spun fables — illustrated tales for kids, at fable.tr.",
    spec: "AI · Storytelling",
    year: "2025",
    status: "LIVE",
    href: "https://fable.tr",
    image: "/fablespun.webp",
  },
  /* 3 — Games */
  {
    ...blank,
    cat: "AK 3-0088",
    band: 3,
    name: "A Dark Room",
    description: "A 1:1 port of the minimalist survival classic to Gleam + Lustre — an offline PWA.",
    spec: "Gleam · Lustre · PWA",
    year: "2025",
    status: "PLAYABLE",
    href: "https://adarkroom.coze.org",
    repo: "https://github.com/c0ze/adarkroom-gleam",
    image: "/adarkroom.webp",
    featured: true,
  },
  {
    ...blank,
    cat: "AK 3-0081",
    band: 3,
    name: "Zork I–III",
    description: "The trilogy, web-playable and illustrated with AI scene art and narration.",
    spec: "Static Web · AI Art",
    year: "2025",
    status: "PLAYABLE",
    href: "https://zork.coze.org",
    repo: "https://github.com/c0ze/zork",
    image: "/zork.webp",
  },
  {
    ...blank,
    cat: "AK 3-0077",
    band: 3,
    name: "The Slimy Lichmummy",
    description: "A faithful Go port of Ulf Åström's terminal roguelike, true to version 0.40.",
    spec: "Go · Terminal",
    year: "2025",
    status: "PLAYABLE",
    href: "https://tsl.coze.org",
    repo: "https://github.com/c0ze/tsl-go",
    image: "/tsl.webp",
  },
  {
    ...blank,
    cat: "AK 3-0064",
    band: 3,
    name: "TankFury",
    description: "A retro-style action game. Take control and fight your way through enemy lines.",
    spec: "Action · Retro",
    year: "2024",
    status: "PLAYABLE",
    href: "https://tankfury.arda.tr",
    image: "/commando.webp",
  },
  {
    ...blank,
    cat: "AK 3-0058",
    band: 3,
    name: "Hackerman",
    description: "Dive into the digital realm with this hacking simulation. Test your skills and breach the system.",
    spec: "Simulation · Puzzle",
    year: "2024",
    status: "PLAYABLE",
    href: "https://hackerman.arda.tr",
    image: "/hackerman.webp",
  },
  {
    ...blank,
    cat: "AK 3-0052",
    band: 3,
    name: "Domino Game",
    description: "A classic Domino game built with Love2D and Lua. Play against the computer in this web-based version.",
    spec: "Lua · Love2D",
    year: "2024",
    status: "PLAYABLE",
    href: "https://domino.arda.tr",
    image: "/domino.webp",
  },
  /* 4 — Writing */
  {
    ...blank,
    cat: "AK 4-0201",
    band: 4,
    name: "blog.arda.tr",
    description: "Notes on systems, languages, and whatever is currently being taken apart.",
    spec: "Astro",
    year: "2024→",
    status: "LIVE",
    href: "https://blog.arda.tr",
  },
  /* 5 — Tools */
  {
    ...blank,
    cat: "AK 5-0155",
    band: 5,
    name: "Reliquary",
    description: "Qdrant-backed long-term memory for AIs, served over MCP.",
    spec: "MCP · Qdrant",
    year: "2025",
    status: "SOURCE",
    repo: "https://github.com/c0ze/reliquary",
    image: "/reliquary.webp",
  },
  {
    ...blank,
    cat: "AK 5-0149",
    band: 5,
    name: "Local AI",
    description: "AI agents running entirely in your browser.",
    spec: "Browser · Agents",
    year: "2025",
    status: "LIVE",
    href: "https://local-ai.arda.tr/",
    repo: "https://github.com/c0ze/local-ai",
    image: "/local-ai.webp",
  },
  {
    ...blank,
    cat: "AK 5-0140",
    band: 5,
    name: "ai.arda.tr",
    description: "AI chatbot that answers questions about my résumé.",
    spec: "AI · Chatbot",
    year: "2025",
    status: "LIVE",
    href: "https://ai.arda.tr/",
    repo: "https://github.com/c0ze/ai.arda.tr",
    image: "/ai-arda.webp",
  },
  {
    ...blank,
    cat: "AK 5-0134",
    band: 5,
    name: "Süper Lig",
    description: "Süper Lig fixtures, results, and live match flow.",
    spec: "Live Scores",
    year: "2025",
    status: "LIVE",
    href: "https://super-lig.arda.tr/",
    repo: "https://github.com/c0ze/super-lig",
    image: "/super-lig.webp",
  },
  {
    ...blank,
    cat: "AK 5-0112",
    band: 5,
    name: "Music Video Upscaler",
    description: "Scripts to build high-quality, upscaled music videos.",
    spec: "Video · Scripts",
    year: "2024",
    status: "SOURCE",
    repo: "https://github.com/c0ze/music-video-upscaler",
    image: "/music-upscaler.webp",
  },
  {
    ...blank,
    cat: "AK 5-0103",
    band: 5,
    name: "Chrome Downloader",
    description: "A simple Chrome extension to download videos.",
    spec: "Chrome · Extension",
    year: "2024",
    status: "SOURCE",
    repo: "https://github.com/c0ze/chrome-dl-extension",
    image: "/chrome-dl.webp",
  },
  /* 6 — Recorded */
  {
    ...blank,
    cat: "AK 6-0031",
    band: 6,
    name: "Pagan",
    description: "Atmospheric black metal from Turkey. Dark, melodic, and aggressive.",
    spec: "Black Metal · LP",
    year: "—",
    status: "RELEASED",
    href: "https://pagan.tr",
    image: "/pagan.webp",
    featured: true,
    invertOnLight: true,
  },
  /* 7 — Composed */
  {
    ...blank,
    cat: "AK 7-0026",
    band: 7,
    name: "Arda",
    description: "Elven laments in J.R.R. Tolkien's Sindarin, written in Tengwar with English translations.",
    spec: "Sindarin · Dark Folk",
    year: "2025",
    status: "RELEASED",
    href: "https://lind.arda.tr",
    image: "/arda.webp",
  },
  {
    ...blank,
    cat: "AK 7-0022",
    band: 7,
    name: "The Seventh Shadow",
    description: "AI generated gothic metal exploring themes of alienation and artificiality.",
    spec: "Gothic Metal · AI",
    year: "2024",
    status: "RELEASED",
    href: "https://distrokid.com/hyperfollow/the7thshadow/alienation-by-design-2",
    image: "/7th-shadow.webp",
  },
]

let kindFor = band =>
  switch kinds->Array.find(k => k.band == band) {
  | Some(k) => k
  | None => {band, name: "Archive", note: "retired"}
  }

let countFor = band => entries->Array.filter(e => e.band == band)->Array.length

let featured = entries->Array.filter(e => e.featured)
