/* The catalogue. One table, many kinds — a Kubernetes migration and a black
   metal record are the same kind of object here, distinguished only by band.

   `band` maps to the IEC 60062 resistor colour code (see DESIGN.md). It is the
   only thing colour encodes in this system. Every band is paired with its kind
   name in the markup so colour is never the sole signal. */

type kind = {
  band: int,
  name: string,
  note: string,
}

type entry = {
  cat: string,
  band: int,
  name: string,
  description: string,
  spec: string,
  year: string,
  status: string,
  href: string,
  repo: string,
  image: string,
  featured: bool,
  containImage: bool,
  invertOnLight: bool,
}

let catalogueNo = "No.1"
let revision = "2026.09"

let kinds: array<kind> = [
  {band: 1, name: "Systems", note: "infrastructure & architecture"},
  {band: 2, name: "Products", note: "shipped applications"},
  {band: 3, name: "Games", note: "originals & ports"},
  {band: 4, name: "Writing", note: "essays & notes"},
  {band: 5, name: "Tools", note: "open source utilities"},
  {band: 6, name: "Recorded", note: "released music"},
  {band: 7, name: "Composed", note: "generated & written music"},
]

let blank = {
  cat: "",
  band: 8,
  name: "",
  description: "",
  spec: "",
  year: "",
  status: "",
  href: "",
  repo: "",
  image: "",
  featured: false,
  containImage: false,
  invertOnLight: false,
}

let entries: array<entry> = [
  /* 1 — Systems */
  {
    ...blank,
    cat: "AK 1-0011",
    band: 1,
    name: "Legacy ↔ AI Integration",
    description: "Systems Architect at Veltra. Integrating legacy applications with AI over MCP; infrastructure on AWS and Kubernetes.",
    spec: "MCP · AWS · K8s",
    year: "2024→",
    status: "ACTIVE",
  },
  {
    ...blank,
    cat: "AK 1-0004",
    band: 1,
    name: "Embedded Processor Design",
    description: "PhD studies in embedded processor design and optimization, following an M.Sc. in Computer Science at Keio University.",
    spec: "Keio · Research",
    year: "2008",
    status: "ARCHIVED",
  },
  /* 2 — Products */
  {
    ...blank,
    cat: "AK 2-0142",
    band: 2,
    name: "SUDONE",
    description: "Scan a shelf barcode in a shop and check whether the price beats online. Keeps a private price notebook.",
    spec: "Flutter · Barcode",
    year: "2026",
    status: "LIVE",
    href: "https://sudone.jp",
    image: "/sudone.webp",
    featured: true,
  },
  {
    ...blank,
    cat: "AK 2-0131",
    band: 2,
    name: "Vigil.today",
    description: "Reminder widget PWA for recurring tasks.",
    spec: "SvelteKit · Firebase",
    year: "2025",
    status: "LIVE",
    href: "https://vigil.today",
    image: "/vigil-today.webp",
  },
  {
    ...blank,
    cat: "AK 2-0128",
    band: 2,
    name: "Skriv.ist",
    description: "Multiplatform ebook reader.",
    spec: "Multiplatform",
    year: "2025",
    status: "LIVE",
    href: "https://skriv.ist",
    image: "/skrivist_logo_3.webp",
    containImage: true,
  },
  {
    ...blank,
    cat: "AK 2-0119",
    band: 2,
    name: "Fablespun",
    description: "Illustrated fables for kids, generated with AI.",
    spec: "AI · Storytelling",
    year: "2025",
    status: "LIVE",
    href: "https://fable.tr",
    image: "/fablespun.webp",
  },
  /* 3 — Games */
  {
    ...blank,
    cat: "AK 3-0101",
    band: 3,
    name: "G Copy",
    description: "A floppy-disk copying business inside an Amiga-style copier, after X-Copy. Plays in the browser.",
    spec: "Lua · LÖVE · Web",
    year: "2026",
    status: "PLAYABLE",
    href: "https://g-copy.gand.games",
    repo: "https://github.com/gandtr/g-copy.gand.games",
    image: "/g-copy.webp",
  },
  {
    ...blank,
    cat: "AK 3-0098",
    band: 3,
    name: "Gage",
    description: "Chess on X, one tweet per move, with no Twitter API. A browser extension draws the board in the page.",
    spec: "Browser extension",
    year: "2026",
    status: "LIVE",
    href: "https://gage.coze.org",
    repo: "https://github.com/c0ze/gage.coze.org",
    image: "/gage.webp",
  },
  {
    ...blank,
    cat: "AK 3-0096",
    band: 3,
    name: "COMMIT!!!",
    description: "A software-career sim. The legacy monolith is the final boss. On Steam and Android.",
    spec: "Simulation · Android · Steam",
    year: "2026",
    status: "RELEASED",
    href: "https://commit.gand.tr",
    image: "/commit.webp",
    featured: true,
  },
  {
    ...blank,
    cat: "AK 3-0094",
    band: 3,
    name: "Gand Games",
    description: "Games label of Gand, an independent studio in Istanbul and Tokyo.",
    spec: "Studio · Label",
    year: "2026",
    status: "LIVE",
    href: "https://gand.games",
    image: "/gandgames.webp",
  },
  {
    ...blank,
    cat: "AK 3-0088",
    band: 3,
    name: "A Dark Room",
    description: "A 1:1 port of the browser survival game to Gleam and Lustre. Works offline as a PWA.",
    spec: "Gleam · Lustre · PWA",
    year: "2025",
    status: "PLAYABLE",
    href: "https://adarkroom.coze.org",
    repo: "https://github.com/c0ze/adarkroom-gleam",
    image: "/adarkroom.webp",
  },
  {
    ...blank,
    cat: "AK 3-0081",
    band: 3,
    name: "Zork I–III",
    description: "The Zork trilogy in the browser, with AI-generated scene art and narration.",
    spec: "Static Web · AI Art",
    year: "2025",
    status: "PLAYABLE",
    href: "https://zork.coze.org",
    repo: "https://github.com/c0ze/zork",
    image: "/zork.webp",
  },
  {
    ...blank,
    cat: "AK 3-0077",
    band: 3,
    name: "The Slimy Lichmummy",
    description: "Go port of Ulf Åström's terminal roguelike, matching version 0.40.",
    spec: "Go · Terminal",
    year: "2025",
    status: "PLAYABLE",
    href: "https://tsl.coze.org",
    repo: "https://github.com/c0ze/tsl-go",
    image: "/tsl.webp",
  },
  /* 4 — Writing */
  {
    ...blank,
    cat: "AK 4-0201",
    band: 4,
    name: "blog.arda.tr",
    description: "Notes on systems and programming languages.",
    spec: "Astro",
    year: "2024→",
    status: "LIVE",
    href: "https://blog.arda.tr",
  },
  /* 5 — Tools */
  {
    ...blank,
    cat: "AK 5-0167",
    band: 5,
    name: "tenioha",
    description: "An experimental functional language in which Japanese particles are checked parts of a function signature.",
    spec: "Python · Language",
    year: "2026",
    status: "LIVE",
    href: "https://c0ze.github.io/tenioha/",
    repo: "https://github.com/c0ze/tenioha",
    image: "/tenioha.webp",
  },
  {
    ...blank,
    cat: "AK 5-0164",
    band: 5,
    name: "Omarchy themes",
    description: "Omarchy desktop themes built from the palettes of Gand, COMMIT!!! and Pagan.",
    spec: "Linux · Hyprland",
    year: "2026",
    status: "SOURCE",
    repo: "https://github.com/c0ze/omarchy-themes",
    image: "/omarchy-themes.webp",
  },
  {
    ...blank,
    cat: "AK 5-0161",
    band: 5,
    name: "cozy-tracker",
    description: "Adaptive game music. Claude writes Impulse Tracker modules, a human edits them, and the same files play in the browser and in games.",
    spec: "JavaScript · libopenmpt",
    year: "2026",
    status: "LIVE",
    href: "https://tracker.coze.org",
    repo: "https://github.com/c0ze/cozy-tracker",
    image: "/cozy-tracker.webp",
  },
  {
    ...blank,
    cat: "AK 5-0158",
    band: 5,
    name: "tincan",
    description: "Message passing between AI coding agents (Claude Code, Codex, Gemini) through a spool on disk. No server.",
    spec: "Go · CLI · MCP",
    year: "2026",
    status: "SOURCE",
    repo: "https://github.com/c0ze/tincan",
    image: "/tincan.webp",
  },
  {
    ...blank,
    cat: "AK 5-0155",
    band: 5,
    name: "Reliquary",
    description: "Qdrant-backed long-term memory for AIs, served over MCP.",
    spec: "MCP · Qdrant",
    year: "2025",
    status: "SOURCE",
    repo: "https://github.com/c0ze/reliquary",
    image: "/reliquary.webp",
  },
  {
    ...blank,
    cat: "AK 5-0149",
    band: 5,
    name: "Local AI",
    description: "AI agents running entirely in your browser.",
    spec: "Browser · Agents",
    year: "2025",
    status: "LIVE",
    href: "https://local-ai.arda.tr/",
    repo: "https://github.com/c0ze/local-ai",
    image: "/local-ai.webp",
  },
  {
    ...blank,
    cat: "AK 5-0140",
    band: 5,
    name: "ai.arda.tr",
    description: "AI chatbot that answers questions about my résumé.",
    spec: "AI · Chatbot",
    year: "2025",
    status: "LIVE",
    href: "https://ai.arda.tr/",
    repo: "https://github.com/c0ze/ai.arda.tr",
    image: "/ai-arda.webp",
  },
  {
    ...blank,
    cat: "AK 5-0134",
    band: 5,
    name: "Süper Lig",
    description: "Süper Lig fixtures, results and live scores.",
    spec: "Live Scores",
    year: "2025",
    status: "LIVE",
    href: "https://super-lig.arda.tr/",
    repo: "https://github.com/c0ze/super-lig",
    image: "/super-lig.webp",
  },
  {
    ...blank,
    cat: "AK 5-0112",
    band: 5,
    name: "Music Video Upscaler",
    description: "Scripts that upscale music videos.",
    spec: "Video · Scripts",
    year: "2024",
    status: "SOURCE",
    repo: "https://github.com/c0ze/music-video-upscaler",
    image: "/music-upscaler.webp",
  },
  {
    ...blank,
    cat: "AK 5-0103",
    band: 5,
    name: "Chrome Downloader",
    description: "Chrome extension for downloading videos.",
    spec: "Chrome · Extension",
    year: "2024",
    status: "SOURCE",
    repo: "https://github.com/c0ze/chrome-dl-extension",
    image: "/chrome-dl.webp",
  },
  /* 6 — Recorded */
  {
    ...blank,
    cat: "AK 6-0031",
    band: 6,
    name: "Pagan",
    description: "Atmospheric black metal from Turkey.",
    spec: "Black Metal · LP",
    year: "—",
    status: "RELEASED",
    href: "https://pagan.tr",
    image: "/pagan.webp",
    featured: true,
    invertOnLight: true,
  },
  /* 7 — Composed */
  {
    ...blank,
    cat: "AK 7-0026",
    band: 7,
    name: "Arda",
    description: "Songs in Tolkien's Sindarin, with lyrics in Tengwar and English translations.",
    spec: "Sindarin · Dark Folk",
    year: "2025",
    status: "RELEASED",
    href: "https://lind.arda.tr",
    image: "/arda.webp",
  },
  {
    ...blank,
    cat: "AK 7-0022",
    band: 7,
    name: "The Seventh Shadow",
    description: "AI-generated gothic metal about alienation and artificiality.",
    spec: "Gothic Metal · AI",
    year: "2024",
    status: "RELEASED",
    href: "https://distrokid.com/hyperfollow/the7thshadow/alienation-by-design-2",
    image: "/7th-shadow.webp",
  },
]

let kindFor = band =>
  switch kinds->Array.find(k => k.band == band) {
  | Some(k) => k
  | None => {band, name: "Archive", note: "retired"}
  }

let countFor = band => entries->Array.filter(e => e.band == band)->Array.length

let featured = entries->Array.filter(e => e.featured)
