type item = {
  title: string,
  description: string,
  image: string,
  link: string,
  tags: array<string>,
  playable: bool,
  containImage: bool,
  repo: option<string>,
}

type section = {
  eyebrow: string,
  title: string,
  description: string,
  items: array<item>,
}

let sections: array<section> = [
  {
    eyebrow: "02 — Projects",
    title: "Projects",
    description: "A collection of digital products and interactive experiences I've built.",
    items: [
      {
        title: "Vigil.today",
        description: "Smart reminder widget PWA that keeps you on track with recurring tasks.",
        image: "/vigil-today.png",
        link: "https://vigil.today",
        tags: ["SvelteKit", "PWA", "Firebase"],
        playable: false,
        containImage: false,
        repo: None,
      },
      {
        title: "Skriv.ist",
        description: "Multiplatform ebook reader.",
        image: "/skrivist_logo_3.png",
        link: "https://skriv.ist",
        tags: ["Ebook", "Reader", "Multiplatform"],
        playable: false,
        containImage: false,
        repo: None,
      },
      {
        title: "Fablespun",
        description: "AI-spun fables — illustrated tales for kids, at fable.tr.",
        image: "/fablespun.png",
        link: "https://fable.tr",
        tags: ["AI", "Storytelling", "Children Books"],
        playable: false,
        containImage: false,
        repo: None,
      },
    ],
  },
  {
    eyebrow: "03 — Games",
    title: "Games",
    description: "A collection of web-based games I've developed.",
    items: [
      {
        title: "Domino Game",
        description: "A classic Domino game built with Love2D and Lua. Play against the computer in this web-based version.",
        image: "/domino.png",
        link: "https://domino.arda.tr",
        tags: ["Lua", "Love2D", "Game Dev"],
        playable: true,
        containImage: false,
        repo: None,
      },
      {
        title: "Hackerman",
        description: "Dive into the digital realm with this hacking simulation. Test your skills and breach the system.",
        image: "/hackerman.png",
        link: "https://hackerman.arda.tr",
        tags: ["Simulation", "Puzzle", "Web Game"],
        playable: true,
        containImage: false,
        repo: None,
      },
      {
        title: "TankFury",
        description: "A retro-style action game. Take control and fight your way through enemy lines.",
        image: "/commando.png",
        link: "https://tankfury.arda.tr",
        tags: ["Action", "Retro", "Web Game"],
        playable: true,
        containImage: false,
        repo: None,
      },
    ],
  },
  {
    eyebrow: "04 — Tools",
    title: "Tools",
    description: "Utilities and tools I've built. Open ones are deployed — click the image to visit; the GitHub icon opens the source.",
    items: [
      {
        title: "ai.arda.tr",
        description: "AI chatbot that answers questions about my résumé.",
        image: "/ai-arda.png",
        link: "https://ai.arda.tr/",
        tags: ["AI", "Chatbot", "Resume"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/ai.arda.tr"),
      },
      {
        title: "Süper Lig",
        description: "Süper Lig fixtures, results, and live match flow.",
        image: "/super-lig.png",
        link: "https://super-lig.arda.tr/",
        tags: ["Football", "Live Scores", "Web"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/super-lig"),
      },
      {
        title: "Local AI",
        description: "AI agents running entirely in your browser.",
        image: "/local-ai.png",
        link: "https://local-ai.arda.tr/",
        tags: ["AI", "Browser", "Agents"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/local-ai"),
      },
      {
        title: "Reliquary",
        description: "Qdrant-backed long-term memory for AIs, served over MCP.",
        image: "/reliquary.png",
        link: "",
        tags: ["MCP", "Mem0", "Qdrant"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/reliquary"),
      },
      {
        title: "Chrome Downloader",
        description: "A simple Chrome extension to download videos.",
        image: "/chrome-dl.png",
        link: "",
        tags: ["Chrome", "Extension", "Video"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/chrome-dl-extension"),
      },
      {
        title: "Music Video Upscaler",
        description: "Scripts to build high-quality, upscaled music videos.",
        image: "/music-upscaler.png",
        link: "",
        tags: ["Video", "Upscaling", "Scripts"],
        playable: false,
        containImage: false,
        repo: Some("https://github.com/c0ze/music-video-upscaler"),
      },
    ],
  },
]
